# Generated by Django 5.0 on 2024-06-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insbiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankdetail",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor",
                to="insbiz.doctor",
            ),
        ),
    ]
