# Generated by Django 5.0 on 2024-06-04 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insbiz", "0002_alter_bankdetail_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankdetail",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_detail",
                to="insbiz.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="status",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status",
                to="insbiz.doctor",
            ),
        ),
    ]
