# Generated by Django 5.0 on 2024-06-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insbiz", "0006_paymenthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="hostel",
            field=models.IntegerField(null=True),
        ),
    ]
