# Generated by Django 5.0 on 2024-06-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insbiz", "0007_paymenthistory_hostel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="gross_stipend",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="itax",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="others",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="utility_bills",
            field=models.IntegerField(null=True),
        ),
    ]
