# Generated by Django 5.0 on 2024-06-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insbiz", "0008_alter_paymenthistory_gross_stipend_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymenthistory",
            name="net_stipend",
            field=models.IntegerField(null=True),
        ),
    ]
