# Generated by Django 5.0 on 2024-06-10 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("insbiz", "0009_alter_paymenthistory_net_stipend"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentHistory",
        ),
    ]
