# Generated by Django 5.0 on 2024-06-10 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insbiz", "0010_delete_paymenthistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("account_title", models.CharField(max_length=225)),
                ("iban", models.CharField(max_length=225)),
                ("gross_stipend", models.IntegerField()),
                ("itax", models.IntegerField()),
                ("hostel", models.IntegerField()),
                ("utility_bills", models.IntegerField()),
                ("others", models.IntegerField()),
                ("net_stipend", models.IntegerField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="insbiz.doctor"
                    ),
                ),
            ],
        ),
    ]
