# Generated by Django 5.0 on 2024-06-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insbiz", "0011_paymenthistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="pmdc",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
