# Generated by Django 5.0 on 2024-06-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insbiz", "0012_alter_doctor_pmdc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
