# Generated by Django 5.0 on 2024-07-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insbiz", "0013_alter_doctor_end_date_alter_doctor_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_total", models.IntegerField(default=0)),
            ],
        ),
    ]
